name: Production Branch Deployment

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive application build
        run: |
          mkdir app
          cp -r alembic api qa_tests scripts tests requirements.txt *.py alembic.ini app
          tar -czf python-prod.tar.gz app
      - name: Copy Artifacts to server
        run: |
          sshpass -p ${{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no python-prod.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/tmp/python
          rm -f python-prod.tar.gz
      - name: Use SSH Action
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd boilerplate/python/prod
            tar -xzf /tmp/python/python-prod.tar.gz -C .
            rm -f /tmp/python/python-prod.tar.gz
            cp .env app/.env
            source venv/bin/activate
            cd app
            pip install -r requirements.txt
            alembic revision --autogenerate
            alembic upgrade head
